# Generated by Django 5.2.17 on 2026-09-29 22:33

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("contenido", models.TextField()),
                ("publicado", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                ("tags", models.CharField(max_length=300)),
                (
                    "codigo",
                    models.CharField(
                        default=post.models.generar_codigo, max_length=32, unique=True
                    ),
                ),
            ],
        ),
    ]
